### ISSUE TITLE
Vagrant Up Error -- Failed to fix the broken static IP for eth1.

### ISSUE THREAD

**Issue by alexpwns** [cyberdefenders/DetectionLabELK#11]
* Operating System Version: Ubuntu Server 20.04.1 LTS with xfce4
* Provider (VirtualBox/VMWare): VirtualBox
* Vagrant Version: 2.2.14
* Packer Version: 1.6.6
* Are you using stock boxes (downloaded) or were they built from scratch using Packer? Stock boxes.
* Is the issue reproducible or intermittent? Reproducible

Please verify that you are building from an updated Master branch before filing an issue.
Pulled the latest master branch today.

### Description of the issue:
I get the following error when I run vagrant up. I tried to grab vagrant_up_$host.log so I could include it in this issue but it doesn't appear to get created.
```
    logger: [+] python-pip was successfully installed!
    logger: Incorrect IP Address settings detected. Attempting to fix.
    logger: Unknown interface eth1
    logger: Unknown interface eth1
    logger: [22:24:18]: Failed to fix the broken static IP for eth1. Exiting because this will cause problems with other VMs.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by lnxg33k** [comment]
@alexpwns I've just rebuilt the lab, and I didn't face any issues, make sure you have an updated box, and feel free to re-open the issue if you are still facing any issues.

**Comment by micksetu** [comment]
@alexpwns I am getting this issue, did you have any success resolving?
