### ISSUE TITLE
How can I move or copy the lab to an offline machine?

### ISSUE THREAD

**Issue by Richard1611** [cyberdefenders/DetectionLabELK#13]
* Operating System Version:Windows Server 2016
* Provider (VirtualBox/VMWare): VirtuLBox
* Vagrant Version:2.2.15
* Packer Version:1.7.2
* Are you using stock boxes (downloaded) or were they built from scratch using Packer?
stock boxes
* Is the issue reproducible or intermittent?
reproducible

Please verify that you are building from an updated Master branch before filing an issue.

### Description of the issue:

I tried to move the entire lab to another machine (a machine without internet), copy the virtualmachines directory and configured virtualbox to use this directory as default for VMs, copied the ~\.vadrant.d and ~\.virtualbox directories also, but when try to start the machines, i got an error.

I also tried to create the same directory that this output tells me, but it didn't works neither. 

###  Error message:

c:\Users\U42857\Downloads\DetectionLab\DetectionLabELK-master\Vagrant>vagrant up
Bringing machine 'logger' up with 'virtualbox' provider...
Bringing machine 'dc' up with 'virtualbox' provider...
Bringing machine 'wef' up with 'virtualbox' provider...
Bringing machine 'win10' up with 'virtualbox' provider...
==> logger: This machine used to live in E:/detectionlabELK/DetectionLabELK-master/Vagrant but it's now at c:/Users/U42857/Downloads/DetectionLab/DetectionLabELK-master/Vagrant.
==> logger: Depending on your current provider you may need to change the name of
==> logger: the machine to run it as a different machine.
Your VM has become "inaccessible." Unfortunately, this is a critical error
with VirtualBox that Vagrant can not cleanly recover from. Please open VirtualBox
and clear out your inaccessible virtual machines or find a way to fix
them.

**Comment by Richard1611** [comment]
> * Operating System Version:Windows Server 2016
> * Provider (VirtualBox/VMWare): VirtuLBox
> * Vagrant Version:2.2.15
> * Packer Version:1.7.2
> * Are you using stock boxes (downloaded) or were they built from scratch using Packer?
>   stock boxes
> * Is the issue reproducible or intermittent?
>   reproducible
> 
> Please verify that you are building from an updated Master branch before filing an issue.
> 
> ### Description of the issue:

**Comment by lnxg33k** [comment]
This is a vagrant-related issue.
