### ISSUE TITLE
build.ps1 on windows, with virtualbox, stop up machine after dc

### ISSUE THREAD

**Issue by ftagliac** [cyberdefenders/DetectionLabELK#7]
* Operating System Version: Windows 10
* Provider (VirtualBox/VMWare): VirtualBox
* Vagrant Version: 2.2.1
* Packer Version: 1.6.2
* Are you using stock boxes (downloaded) or were they built from scratch using Packer? build from packer
* Is the issue reproducible or intermittent? reproduce

Please verify that you are building from an updated Master branch before filing an issue.

### Description of the issue:
build.ps1 on windows, with virtualbox, stop up machine after dc.
I can go ahead manually lauching vagrant up commands
```

**Comment by lnxg33k** [comment]
That works fine for me, please provide a screenshot and feel free to re-open the issue
