### ISSUE TITLE
Error during vagrat up

### ISSUE THREAD

**Issue by dmaynor** [cyberdefenders/DetectionLabELK#8]
* Operating System Version:
* Provider (VirtualBox/VMWare): Virtualbox
* Vagrant Version: 2.2.10
* Packer Version: 1.6.4
* Are you using stock boxes (downloaded) or were they built from scratch using Packer? stock
* Is the issue reproducible or intermittent? reproducable

Please verify that you are building from an updated Master branch before filing an issue.

**Comment by dmaynor** [comment]
In Vagrant/scripts/provision.ps1 if you comment out line 14, the curl command, everything else works.

**Comment by lnxg33k** [comment]
Thanks @dmaynor that was fixed.
