### ISSUE TITLE
is there a plan to support vmware?

### ISSUE THREAD

**Issue by k-alshamsi** [cyberdefenders/DetectionLabELK#9]
im getting this error

==> dc: Box 'cyberdefenders/win2016' could not be found. Attempting to find and install...
    dc: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    dc: Box Version: >= 0
==> dc: Loading metadata for box 'cyberdefenders/win2016'
    dc: URL: https://vagrantcloud.com/cyberdefenders/win2016
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Vagrant Cloud, make sure the box is
released.

Name: cyberdefenders/win2016
Address: https://vagrantcloud.com/cyberdefenders/win2016
Requested provider: ["vmware_desktop", "vmware_fusion", "vmware_workstation"]

which seems to me that VMware is not supported. is there any plans to do so?

**Comment by lnxg33k** [comment]
Hi @k-alshamsi
Unfortunately, we currently support only Virtualbox as a hypervisor.
[DetectionLab](https://github.com/clong/DetectionLab/ ) by @clong supports multiple hypervisors, but it is shipped with Splunk.

You are more than welcome to apply a PR for such a feature.
